/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as MinisteriosRouteImport } from './routes/ministerios'
import { Route as DoacoesRouteImport } from './routes/doacoes'
import { Route as CultosRouteImport } from './routes/cultos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const MinisteriosRoute = MinisteriosRouteImport.update({
  id: '/ministerios',
  path: '/ministerios',
  getParentRoute: () => rootRouteImport,
} as any)
const DoacoesRoute = DoacoesRouteImport.update({
  id: '/doacoes',
  path: '/doacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CultosRoute = CultosRouteImport.update({
  id: '/cultos',
  path: '/cultos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/cultos': typeof CultosRoute
  '/doacoes': typeof DoacoesRoute
  '/ministerios': typeof MinisteriosRoute
  '/online': typeof OnlineRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/cultos': typeof CultosRoute
  '/doacoes': typeof DoacoesRoute
  '/ministerios': typeof MinisteriosRoute
  '/online': typeof OnlineRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/cultos': typeof CultosRoute
  '/doacoes': typeof DoacoesRoute
  '/ministerios': typeof MinisteriosRoute
  '/online': typeof OnlineRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/cultos'
    | '/doacoes'
    | '/ministerios'
    | '/online'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/cultos'
    | '/doacoes'
    | '/ministerios'
    | '/online'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/cultos'
    | '/doacoes'
    | '/ministerios'
    | '/online'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  CultosRoute: typeof CultosRoute
  DoacoesRoute: typeof DoacoesRoute
  MinisteriosRoute: typeof MinisteriosRoute
  OnlineRoute: typeof OnlineRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministerios': {
      id: '/ministerios'
      path: '/ministerios'
      fullPath: '/ministerios'
      preLoaderRoute: typeof MinisteriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doacoes': {
      id: '/doacoes'
      path: '/doacoes'
      fullPath: '/doacoes'
      preLoaderRoute: typeof DoacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultos': {
      id: '/cultos'
      path: '/cultos'
      fullPath: '/cultos'
      preLoaderRoute: typeof CultosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  CultosRoute: CultosRoute,
  DoacoesRoute: DoacoesRoute,
  MinisteriosRoute: MinisteriosRoute,
  OnlineRoute: OnlineRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
